[package]
name = "monotron"
version = "0.3.1"
authors = ["Jorge Aparicio <jorge@japaric.io>", "Jonathan 'theJPster' Pallant <monotron@thejpster.org.uk>"]
description = "A simple 1980's home computer style application for the Stellaris Launchpad."
keywords = ["arm", "cortex-m", "template", "video", "menu"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/thejpster/monotron"

[profile.release]
lto = true
debug = true

[dependencies]

[dependencies.tm4c123x-hal]
git = "https://github.com/thejpster/tm4c123x-hal"
# path = "../tm4c123x-hal"

[dependencies.menu]
git = "https://github.com/thejpster/menu"
# path = "../menu"

[dependencies.vga-framebuffer]
git = "https://github.com/thejpster/vga-framebuffer-rs"
# path = "../vga-framebuffer-rs"

[dependencies.embedded-hal]
version = "0.1.1"
features = ["unproven"]

[dependencies.cortex-m]
version = "0.4.0"

[dependencies.cortex-m-rt]
version = "0.3.15"
features = ["abort-on-panic"]

[dependencies.cortex-m-semihosting]
version = "0.2.0"
